[workspace]
members = [
"librustzcash",
"librustdrivechain",
]

# For faster build times during I disabled optimizations.
[profile.release]
incremental = true
lto = false
panic = 'abort'
codegen-units = 256
