[package]
name = "librustdrivechain"
version = "0.0.1"
authors = [ "Nikita Chashchinskii <nikita.chashchinskii@gmail.com>" ]


[lib]
name = "rustdrivechain"
crate-type = ["staticlib"]

[dependencies]
drivechain = { git = "https://github.com/nchashch/drivechain", rev = "be0454ec99f81c82fd6b008fb914397728b3f9ff" }
