[package]
name = "librustdrivechain"
version = "0.0.1"
authors = [ "Nikita Chashchinskii <nikita.chashchinskii@gmail.com>" ]


[lib]
name = "rustdrivechain"
crate-type = ["staticlib"]

[dependencies]
drivechain = { git = "https://github.com/nchashch/drivechain", rev = "adb918c52aad58bb248b9236ac2b21dd478b78ea" }
